version: '3'
services:
  backend:
    build:
      context: ./spring_backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build:
      context: ./react_frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
