

services:
    frontend:
        container_name: frontend
        build: ./frontend
        ports:
            - "3000:80"
        depends_on:
            - backend
        networks:
            - app-network

    backend:
        container_name: backend
        build: ./backend
        ports:
            - "8080:8080"
        environment:
            - DB_HOST=mysql
            - DB_PORT=3306
            - DB_NAME=database
            - DB_USER=user
            - DB_PASSWORD=password
        depends_on:
            - mysql
        networks:
            - app-network

    mysql:
        image: mysql:latest
        container_name: mysql-database
        environment:
            MYSQL_ROOT_PASSWORD: admin
            MYSQL_DATABASE: database
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        volumes:
            - mysql_data:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - app-network

    backup:
        image: alpine:latest # Use a lightweight base image with utilities
        container_name: mysql-backup
        volumes:
            - ./database:/database
            - ./backups:/backup
        entrypoint: >
            /bin/sh -c "apk add --no-cache bash mysql-client cronie && 
                        chmod +x /database/backup.sh && 
                        crontab -l | { cat; echo '0 * * * * /database/backup.sh'; } | crontab - && 
                        crond -f"

networks:
    app-network:
        driver: bridge

volumes:
    mysql_data: