package project.backend.model;

public enum NotificationType {
    // TODO: Implement me
    ALERT,
    COLLABORATION_REQUEST,
    COLLABORATION_ACCEPTED,
    COLLABORATION_REJECTED,
    COLLABORATION_PENDING,
    COLLABORATION_TERMINATED,
    MEETING_ACCEPTED,
    MEETING_REJECTED,
    MEETING_REQUEST,
    FEEDBACK_SUBMITTED,
}
